# Generated by Django 5.2.11 on 2026-02-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.FloatField()),
                ('minimum_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('recurring', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('recurring', models.BooleanField(default=False)),
            ],
        ),
    ]
